defaults:
  efficiency: 1.0
  technical_lifetime: 30
  opex_cost_energy: 0.0
  opex_cost_power: 0.0
  capex_cost_power: 0.0
  stage: stage1
  category: demand_link

categories:
  grid:
    efficiency: 1.0
    technical_lifetime: 30
    opex_cost_energy: 0.0
    opex_cost_power: 0.0
    capex_cost_power: 0.0
    stage: stage2
    category: grid