site_name: GeoPipe Documentation
theme:
  name: material

nav:
  - Welcome: index.md
  - Getting started: getting_started.md
  - Components:
    - modify_streets_data: Components/modify_streets_data.md
    - TopologyBuilder: Components/topology_builder.md
    - Registering technologies: Components/technologies.md
    - DemandType: Components/demand_type.md
    - DataRegistry: Components/data_registry.md
    - EnergySystemBuilder: Components/energy_system_builder.md
  - CESM extension:
    - NewlyInstalledUnits: CESM extension\newly_installed_units.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
