[build-system]
requires = ["setuptools<81", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pypeline"
version = "0.1.0"
description = "PYthon-based data piPELINe for Energy system modeling"
authors = [
    {name = "Carolin Ayasse", email = "carolin.ayasse@eins.tu-darmstadt.de"},
    {name = "Alexander Christ", email = "alexchrist@outlook.com"},
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "attrs==25.3.0",
    "cesm",
    "contextily==1.6.2",
    "geopandas==1.1.1",
    "matplotlib==3.10.6",
    "numpy==2.2.6",
    "osm2geojson==0.3.1",
    "pandas==2.3.2",
    "plotly==6.3.0",
    "scipy==1.14.1",
    "shapely==2.1.2",
    "sqlalchemy==2.0.43",
    "psycopg2==2.9.10",
    "pyyaml==6.0.3",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.3.5",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["pypeline*", "tools*"]
exclude = ["CESM*", "data*", "examples*", "tests*", "docs*"]

[tool.uv.sources]
cesm = { path = "CESM", editable = true }
