################################
# indirect heating technologies
#################################

ind_heat_pump:
  efficiency: 3.9
  technical_lifetime: 18  # years
  opex_cost_energy: 0     # €/MWh
  opex_cost_power: 13000  # €/MW
  capex_cost_power: 10100 # €/MWh
  capex_cost_base: 10600  # €
  cap_min: 0.005
  cap_max: 0.11

ind_gas_boiler:
  efficiency: 0.94
  technical_lifetime: 20
  opex_cost_energy: 0
  opex_cost_power: 5000
  capex_cost_power: 1620
  capex_cost_base: 7100
  cap_min: 0.01
  cap_max: 0.11

ind_oil_boiler:
  efficiency: 0.925
  technical_lifetime: 20
  opex_cost_energy: 0.0
  opex_cost_power: 6000
  capex_cost_power: 700
  capex_cost_base: 11400
  cap_min: 0.01
  cap_max: 0.11

ind_hydrogen_boiler:
  efficiency: 0.95 
  technical_lifetime: 20
  opex_cost_energy: 0
  opex_cost_power: 100000
  capex_cost_power: 200000
  capex_cost_base: 11400
  cap_min: 0.06
  cap_max: 0.11

heat_exchanger:
  efficiency: 0.99
  technical_lifetime: 25
  opex_cost_energy: 0
  opex_cost_power: 25000
  capex_cost_power: 0
  capex_cost_base: 1360000
  cap_min: 0.01
  cap_max: 100000000.0

################################
# central heating technologies
################################

cen_heat_pump:
  efficiency: 3.1
  technical_lifetime: 28
  opex_cost_energy: 0
  opex_cost_power: 150000
  capex_cost_power: 31000
  capex_cost_base: 53000
  cap_min: 0.3
  cap_max: 20.0

cen_gas_boiler:
  efficiency: 0.99
  technical_lifetime: 25
  opex_cost_energy: 0
  opex_cost_power: 2000
  capex_cost_power: 100000
  capex_cost_base: 65000
  cap_min: 0.5
  cap_max: 10

cen_oil_boiler:
  efficiency: 0.93
  technical_lifetime: 20
  opex_cost_energy: 0
  opex_cost_power: 6500
  capex_cost_power: 149000
  capex_cost_base: 18000
  cap_min: 0.1
  cap_max: 1.0

cen_biomass_woodpellets:
  efficiency: 0.5
  technical_lifetime: 25
  opex_cost_energy: 0
  opex_cost_power: 100
  capex_cost_power: 440000
  capex_cost_base: 260000
  cap_min: 450
  cap_max: 450

heat_grid:
  efficiency: 0.86
  technical_lifetime: 40.0
  cap_min: 1000000.0
  cap_max: 1000000.0
  max_units: 1

grid_electricity:
  commodity_out: electricity
  commodity_in: dummy
  cap_max: 1000000000
  max_units: 1

grid_hydrogen:
  commodity_out: hydrogen
  commodity_in: dummy
  cap_max: 1000000000
  max_units: 1


#############################
# hidden from region builder
#############################

heat_pipe:
  efficiency: 0.96
  technical_lifetime: 40.0
  opex_cost_power: 0.0
  opex_cost_energy: 1.44
  pipe_capex_eur_per_km: 1000000.0 # €/km
  cap_min: 100000.0
  cap_max: 100000.0