################################
# indirect heating technologies
#################################

ind_heat_pump:
  efficiency: 4.1
  technical_lifetime: 18
  opex_cost_energy: 0
  opex_cost_power: 76000
  capex_cost_power: 2780000
  capex_cost_base: 13900
  cap_min: 0.005
  cap_max: 0.11

ind_gas_boiler:
  efficiency: 0.94
  technical_lifetime: 20
  opex_cost_energy: 0
  opex_cost_power: 5000
  capex_cost_power: 274000
  capex_cost_base: 11400
  cap_min: 0.01
  cap_max: 0.11

ind_oil_boiler:
  efficiency: 0.925
  technical_lifetime: 20
  opex_cost_energy: 0
  opex_cost_power: 6000
  capex_cost_power: 291000
  capex_cost_base: 11400
  cap_min: 0.01
  cap_max: 0.11

ind_hydrogen_boiler:
  efficiency: 0.994 
  technical_lifetime: 20
  opex_cost_energy: 0
  opex_cost_power: 100000
  capex_cost_power: 177000
  capex_cost_base: 10900
  cap_min: 0.06
  cap_max: 0.11

heat_exchanger:
  efficiency: 0.99
  technical_lifetime: 25
  opex_cost_energy: 0
  opex_cost_power: 25000
  capex_cost_power: 0
  capex_cost_base: 1360000

################################
# central heating technologies
################################

cen_heat_pump:
  efficiency: 2.9
  technical_lifetime: 28
  opex_cost_energy: 0
  opex_cost_power: 22000
  capex_cost_power: 585593
  capex_cost_base: 823281
  cap_min: 0.3
  cap_max: 20

cen_gas_boiler:
  efficiency: 0.99
  technical_lifetime: 25
  opex_cost_energy: 1.3
  opex_cost_power: 1100
  capex_cost_power: 105579
  capex_cost_base: 12210
  cap_min: 0.5
  cap_max: 10

cen_oil_boiler:
  efficiency: 0.93
  technical_lifetime: 20
  opex_cost_energy: 2.45
  opex_cost_power: 1500
  capex_cost_power: 145556
  capex_cost_base: 3444
  cap_min: 0.1
  cap_max: 1

cen_biomass_woodpellets:
  efficiency: 0.9
  technical_lifetime: 28
  opex_cost_energy: 3
  opex_cost_power: 5158
  capex_cost_power: 439000
  capex_cost_base: 260000
  cap_min: 5.8
  cap_max: 5.8

##################
# grids and pipes
##################

heat_grid:
  {}

grid_electricity:
  commodity_out: electricity
  commodity_in: dummy

grid_hydrogen:
  commodity_out: hydrogen
  commodity_in: dummy

# heat pipes for district-level connections
heat_pipe:
  efficiency: 0.98
  technical_lifetime: 30
  opex_cost_energy: 0.0
  capex_cost_power: 100.0
  cap_max: 1000000000